{
 "title": "AIRFLOW - All DAGs [Discovery API]",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dags",
    "label": "DAG",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$dags dagRuns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "dagRun | Last state",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$dags" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "GCP" },
     "host": { "filter": "cerc-airflow-monitor-prd" },
     "item": {
      "filter": "/\\[$dags\\] Last dagRun state number/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "dagRun | History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$dags" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "GCP" },
     "host": { "filter": "cerc-airflow-monitor-prd" },
     "item": {
      "filter": "/\\[$dags\\] Last dagRun state number/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "dagRun | JSON Last",
   "type": "logs",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$dags" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "GCP" },
     "host": { "filter": "cerc-airflow-monitor-prd" },
     "item": { "filter": "/\\[$dags\\] Last dagRun/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "[$dags] [Tasks] Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "DAG | Is State",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/\\[$dags\\] Details/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "DAG | Crontab",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 2, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/\\[$dags\\] Details/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "DAG | Owners",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 5, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/\\[$dags\\] Details/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Tasks Instances | JSON Details",
     "type": "logs",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "/\\[$dags\\] dagRuns Task Instances/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Tasks | JSON Details",
     "type": "logs",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 13 },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/\\[$dags\\] Tasks/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "DAG | JSON Details",
     "type": "logs",
     "gridPos": { "h": 16, "w": 7, "x": 0, "y": 15 },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/\\[$dags\\] Details/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Tasks Instances SLAMISS | JSON Details",
     "type": "logs",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "/\\[$dags\\] \\[slamiss\\] dagRuns Task Instances/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Tasks | JSON Task_id",
     "type": "logs",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 24 },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/\\[$dags\\] All Tasks ID/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "dagSources | JSON Details",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$dags" ],
         "text": "setAlias()"
        }
       ],
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/\\[$dags\\] dagSources/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "[All] DAGs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "DAG Dependencies | Flowchart",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 14 },
     "options": {
      "content": "graph LR\n      updatedeffects[updated_effects] --> waitdagupdatedeffects(wait_dag_updated_effects)\n      waitdagupdatedeffects --> partialeffects[partial_delta_updated_effects]\n      partialeffects --> waitdeltaupdatedeffects(wait_partial_delta_updated_effects)\n      waitdeltaupdatedeffects --> deltaeffects[delta_updated_effects]\n      deltaeffects --> triggerContractEffect{trigger_update_ContractEffect}\n      triggerContractEffect --> updateContractEffectHistory[update_ContractEffectHistory]\n      deltaeffects --> triggertrigger{trigger_ap005_trigger}\n      triggertrigger --> ap005trigger[ap005_trigger]\n      ap005trigger --> triggerasset{trigger_ap005_effects_without_asset}\n      triggerasset --> ap005asset[ap005_effects_without_asset] \n      ap005trigger --> triggerwhitheffects{trigger_ap005_asset_with_effects}\n      triggerwhitheffects --> ap005witheffects[ap005_asset_with_effects]\n      ap005witheffects --> triggerwithouteffects{trigger_ap005_asset_without_effects}\n      triggerwithouteffects --> ap005withouteffects[ap005_asset_without_effects]\n      generateeffect[generate_contract_effect] --> triggerhistory{trigger_updated_history}\n      triggerhistory --> updateContractEffectHistory\n      generateeffect --> triggerinterop{trigger_interop}\n      triggerinterop --> interopsent[interop_sent]\n      ap013table[ap013_prepare_table] --> triggernew{trigger_ap013_new}\n      triggernew --> ap013new[ap013_new]\n      ap013table --> triggernormal{trigger_ap013_normal}\n      triggernormal --> ap013normal[ap013_normal]\n      ap010bvalidatetiofiles[ap010b_load_and_validate_tio_files] --> waitexecution(wait_last_execution)\n      ap010bcomparetiofiles[ap010b_compare_tio_files] --> waitfiles(wait_dag_ap010b_compare_tio_files)\n      waitfiles --> ap010bresults[ap010b_send_compare_results]\n      waitfiles --> ap010bbk[ap010_load_and_compare_bk]\n      ap010bbk --> waitbk(wait_dag_ap010b_load_and_compare_bk)\n      waitbk --> ap010bresults\n      tempcontracteffect[temp_new_contracteffect] --> triggerinterop\n      ap005trigger --> waitap005[wait_ap005]\n      dumpinterop[dump_book_keeping_interop] --> triggerdecompress{trigger_decompress}\n      triggerdecompress --> decompressflow[decompress_batch_payment_flow]\n      decompressflow --> waitflow(wait_decompress_batch_payment_flow)\n      waitflow --> ap005interop[ap005_interop]\n      waitap005 --> ap005interop      \n      ap005interop --> triggerinfo{trigger_ap005_optins_whitout_info}\n      triggerinfo --> ap005info[ap005_optins_whitout_info]\n      syncbq[sync_spanner_to_bq] --> waitdump(wait_dump)\n      waitdump --> decompressflow"
     },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[updated_effects] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[partial_delta_updated_effects] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[delta_updated_effects] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[generate_contract_effect] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[update_ContractEffectHistory] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[delta_updated_effects] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[interop_sent] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap013_prepare_table] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap013_new] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap013_normal] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap010b_compare_tio_files] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap010b_load_and_compare_bk] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap010b_send_compare_results] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[temp_new_contracteffect] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap005_trigger] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[dump_book_keeping_interop] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[sync_spanner_to_bq] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[decompress_batch_payment_flow] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap005_interop] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap005_optins_without_info] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap005_effects_without_asset] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap005_asset_with_effects] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": {
        "filter": "[ap005_asset_without_effects] Last dagRun state number"
       },
       "itemTag": {
        "filter": "airflow: Last dagRun state number"
       },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "timeSeriesList": {
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "perSeriesAligner": "ALIGN_MEAN",
        "projectName": "cerc-monitoring-prd"
       }
      }
     ]
    },
    {
     "title": "Incidents | History",
     "type": "alexanderzobnin-zabbix-triggers-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "GCP" },
       "host": { "filter": "cerc-airflow-monitor-prd" },
       "item": { "filter": "/$dags/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "count": false,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTimeRange": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "showProblems": "history",
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  }
 ]
}